### ISSUE TITLE
Issue with basic/core bot created via ABS

### ISSUE THREAD

**Issue by swagatmishra2007** [microsoft/BotFramework-Services#135]
I just created a core bot via the ABS portal.
When I say “Hi” to it, I get a “Sorry didn’t get that. Please try asking in a different way (intent was Cancel)”

I am guessing this isn’t expected?
Did something change in the SDK or Luis model?

![image](https://user-images.githubusercontent.com/19970037/65556466-97ab3380-dee4-11e9-8bc8-c5360bb454fc.png)

**Comment by jwiley84** [comment]
The standard core bot has ‘LUIS-like’ logic to mimic what LUIS would look like. It would seem that that ‘hi’ triggered either a “none” intent mimic, or fell through a hole. I’ll check the logic when I get back to the office.

**Comment by jwiley84** [comment]
Alright, this looks like expected behaviour. When the Basic bot was created on Azure, it created a simple 'corebot' LUIS model. Because there was a LUIS model, it routed through the LUIS switch in 'MainDialog.cs' 

![image](https://user-images.githubusercontent.com/17333688/65631888-4f941b80-df8d-11e9-923e-596d4317dab4.png)

While the LUIS model does not have a 'hi' utterance in any of it's intents (Cancel, BookFlight, GetWeather, None), but testing 'hi' in the LUIS portal shows that it returns the Cancel intent at 0.68.

![image](https://user-images.githubusercontent.com/17333688/65632078-b3b6df80-df8d-11e9-85ab-f1ae9dacd2ba.png)


Is it weird? Yes. Is it expected? Also yes.
