### ISSUE TITLE
MS-Team image does not reader with activity text.  

### ISSUE THREAD

**Issue by piyushkacha7** [microsoft/BotFramework-Services#161]
I'm also phasing image rendering issue in MS-Teams. I sent in activity text. some days ago that working but now does not work. 
 
![image](https://user-images.githubusercontent.com/47378765/71661358-f0a42680-2d73-11ea-949a-5afc9326a6ce.png)
Above image both way working before some days. but now result in the below image. 
![image](https://user-images.githubusercontent.com/47378765/71661219-8b503580-2d73-11ea-914b-1475656642bc.png)

**Comment by samirkatyar** [comment]
I'm also facing this issue 
im sending image in this way but still not rendering
`<img src="img_url" alt="Duck on a rock" height="170" width="220"></img>`

**Comment by Bhargav-Kalaria** [comment]
The same issue is been faced by me, near about 15 days.

**Comment by samirkatyar** [comment]
I'm also facing this issue
im sending image in this way but still not rendering
`<img src="img_url" alt="" height="170" width="220"></img>`

**Comment by jwiley84** [comment]
Investigating this, but can I get everyone to post their language and SDK version?

**Comment by jwiley84** [comment]
I cannot repro the issue, but I think that's how the card is being configured in the code. @piyushkacha7, can you post your code on how you're creating the card attachment, so I can attempt a repro of your specific issue?

**Comment by piyushkacha7** [comment]
@jwiley84 Thank you for helping for issue
Language is javascript/Node.js and below package.json 
```
    "botbuilder": "4.5.3",
    "botbuilder-ai": "4.5.3",
    "botbuilder-azure": "4.5.3",
    "botbuilder-dialogs": "4.5.3",
    "botframework-config": "4.5.3",
    "botframework-connector": "4.5.3",
```
I'm does not sending image from card attachment just **sendActivity()** text with image; 
 
```
// construct hero card.
const card = CardFactory.heroCard('', undefined, choiceButtons, {text: ''});

let reply = {type: ActivityTypes.Message};
// add card to Activity.
reply.attachments = [card];
reply.text = `HERE some text with Image  Example: text with <img src="img_url" alt="" height="170" width="220"></img> `;

await step.context.sendActivity(reply);
```
also, I tried with the latest all bot builder package with `4.7.0` but not working on that. 


1) `![Duck on a rock](https://tineye.com/images/widgets/mona.jpg)`
2) `<img src="https://tineye.com/images/widgets/mona.jpg" alt="Duck on a rock" height="150" width="223"></img>`

Above both ways does not work with `await step.context.sendActivity("image with text");`

**Comment by jwiley84** [comment]
Option 2 is not going to work, because according to the Teams bot docs, they don't support img as an html tag in text. I'm not certain why it was supported before, but it is not supported now. It appears that the teams client attempts to render the image link a rich card, and that is not supported:

![image](https://user-images.githubusercontent.com/17333688/71748926-e42dd580-2e28-11ea-94a6-0ca546ba94ff.png)


As for option 1, reading the section of the doc you linked above about sending picture messages, it outright says 'don't use' next to the markdown example.

Again, it's possible that it was previously an option to add an inline image to a text message and send through, but even the doc you linked says 

> Pictures are sent by adding attachments to a message.

The simplest way to do this is like so:

```
//const card= CardFactory.heroCard('', undefined, undefined, {text:''});
const testcard2= 
{
    name: 'robot',
    contentType: 'image/png',
    contentUrl: 'https://publicdomainvectors.org/photos/robot.png'
}
let reply = {type: ActivityTypes.message };
reply.attachments = [testcard2];
reply.text = 'HERE some text with Image. '
await context.sendActivity(reply);
```

This will result in the following (tested using the teams webview):
![image](https://user-images.githubusercontent.com/17333688/71750148-6f5c9a80-2e2c-11ea-9a89-91d856cc3498.png)

Because this issue is so Teams specific, I suggest raising is here, on the [Teams 'Format your bot message' page](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages#formatting-text-content). I'll reach out to a member of the Teams team and see if I can get clarification as well. I will leave this open until I have an official answer.

**Comment by piyushkacha7** [comment]
Okay, thank you for helping. 
Currently, I don't have an option for change format to sending images. If I change image format with an attachment then that's the biggest change for me. For my client, they know image works with text and suddenly if not support by ms-teams then it's difficult so I waiting for an official answer.

**Comment by clearab** [comment]
I don't believe using an inline image tag has ever been supported by Teams - if it was working for a while it was a bug/regression.

**Comment by apurva1112** [comment]
![download](https://user-images.githubusercontent.com/42499837/88284053-581ec500-cd0a-11ea-9c10-3f1be2897215.png)

**Comment by apurva1112** [comment]
![download](https://user-images.githubusercontent.com/42499837/88284103-708edf80-cd0a-11ea-89f0-a26a08af6ab0.png)
