### ISSUE TITLE
Azure BotService BotTemplate

### ISSUE THREAD

**Issue by sherlock666** [microsoft/BotFramework-Services#166]
I remember that Azure Platform - BotService shall support python in v4.6 
But currently still only exist choice for C# & Python
When will Azure Platform - BotService support python

Thanks!!!

**Comment by sherlock666** [comment]
![image](https://user-images.githubusercontent.com/35552608/71949332-0f8c3800-320e-11ea-870f-f7ca261acd27.png)


The SDK Language part
When will it add the button for python?

Thanks!!!

**Comment by v-kydela** [comment]
@jameslew - I'll unassign myself so you can take care of this

**Comment by jameslew** [comment]
Hi @sherlock666 ; right now we're evaluating when to do this.  Often as not we find customers stand up their own web services and then create a Bot Registration rather than using the deployed web app (for long term after trial anyway).

As we plan for this; what expectations would you have of the template?  Environment, OS, etc?

**Comment by jameslew** [comment]
Thanks again @sherlock666 ; I've added your request as a +1 on our backlog item for prioritization.
