### ISSUE TITLE
Same Conversation Id generated for 2 different users

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-Services#183]
## Versions
botbuilder NodeJS SDK v4.6.2
The bot is created in Azure using "Bot Channel Registration" template.

## Description
Our bot service has received messages (over directline channel) from 2 different users (userIds: OkZ7GnABPltEMu1ogKpk and RUaBGnABPltEMu1oEap2) but with the same conversation id (8KiF8gmcold8mpQpsVqasI-h). This has resulted in a corrupted session (of ConversationState scope).

This is a serious issue as our bot session storage architecture assumes that conversation id generated is always unique for a bot.

Not sure if this scenario is considered and expected.
Need your help asap.

**Comment by anusharavindrar** [comment]
@bhushanvadgave can you provide the MicrosoftAppId, BotHandle, and UTC timestamp of when this exactly happened?

**Comment by bhushanvadgave** [comment]
@anusharavindrar
Please find the details below
MicrosoftAppId: ad684b78-c94f-4c5e-be5d-8bcb3ccd9c37
BotHandle: akzo-prod-bot-eukdlx

**Comment by anusharavindrar** [comment]
@bhushanvadgave thank you for the above details. I am currently working with another dev who is looking into this closely. Since the time you reported this, did you experience this behavior again in the last few weeks? We haven't heard of this behavior before, so would be interested in knowing if the same conversation ID was generated again for two different users.

**Comment by anusharavindrar** [comment]
Closing the issue. Feel free to reopen if you are still having issues.
