### ISSUE TITLE
Azure Bot Service OAuth Connection String Not Maintaining Token

### ISSUE THREAD

**Issue by thejasondt** [microsoft/BotFramework-Services#186]
I have recently set up the Oauth Connection String (in settings in my Bot Service in Azure) with the Instagram Basic Display API - however, it seems the Bot Service is not maintaining the token.

It works at first but over time (maybe an hour) I get:

"message": "Error validating access token: Session has expired on Friday, 28-Feb-20 12:00:00 PST. The current time is Friday, 28-Feb-20 15:10:48 PST.",
"type": "OAuthException",
"code": 190,

I believe the issue is that with the IG Basic Display API you get a short term token (1 hour) that you have to trade for a long term token (6 months). I don't believe the bot service is doing this correctly (it is getting the short-term correctly but then perhaps saving and trying to maintain that over 6 months rather than trading it for the 6 months token?), or perhaps there is an issue on my behalf?

Insight here would be great as I would prefer not to maintain the token myself if this solution works.

Can someone replicate this?

**Comment by jwiley84** [comment]
Are you using the Instagram as sevice provider on the Azure portal, or are you using Generic Oauth?

**Comment by thejasondt** [comment]
Instagram

**Comment by jwiley84** [comment]
> I am using it to access their IG, not to allow them to log in with my app via Instagram.

You're going to have to clarify once more. The way you're using the OAuth connection string is to authenticate, but what you're describing is NOT OAuth.

**Comment by jwiley84** [comment]
Doing a bit more digging into the Insta basic display API, I think I can see what you're doing. 

Using this API in the OAuth Connection String is going to return the short-lived token that is only going to last an hour. What you do with that token going forward is on you as the dev, including using it to retrieve a long-lived token (which according to the Insta API docs lasts 60 days). 

In order to ensure your user remains logged in, I recommend you loop your user through a login-verification waterfall. Basically, it checks for a live token with every message and if the token is expired or null, it resends the login prompt.

**Comment by thejasondt** [comment]
I thought the point of using the bot service connection string to authorize is to use the bot service to maintain the token refreshing etc for me? I'm pretty sure that's the reason I saw them say in the video from MS about it. 

Otherwise, I don't really see the point in it. With the previous Instagram API, it maintained the tokens for us, including refreshing. Now, I may as well do the whole cycle myself as I have to refresh/maintain it myself anyway.

**Comment by jwiley84** [comment]
I watched the video you referenced, and while some of the info in it is true, some of it is outdated. 

The Bot Framework Token Service (built using your service provider on the Azure portal) is responsible for using oauth to do the token retrieval, as well as storing that token once acquired. That part is true. The bot dev can use the service to handle all the exchanging of ids and secrets for tokens. They also don't  have to manage securely storing that token themselves. 

The bot dev is responsible to make sure to implement logic that handles when token expires (ie resending the oauth prompt to log the user back in). The logic is simple in that all you have to do is call a check for the token with every message. As for exchanging the short-term oauth token you recieve using the oauth prompt for the longer-lived one in the Insta API, that is on the dev.

**Comment by thejasondt** [comment]
Well we would have to handle the secure long term token storage and refreshing with the current capabilities. 

Also we cannot check the token response with every message as it continues to return the old 1 hour token that has expired.

I assumed this service was to maintain the lifecycle of the token for us, otherwise I am unsure why we would use it more than once. And even then, the check the bot does for a token response again returns the old expired token. It doesn't seem practical

**Comment by jwiley84** [comment]
You would have to maintain the storage of the long-term token, yes, because that is not the standard token returned with an oauth request. 

As for checking the token response, if you run the OauthPrompt dialog, and it returns a response that the token is expired,  it will log the user out and resend the oauth prompt, prompting the user to log in again. That is handled by the Bot Builder Dialogs. 

The video was released in 2018 when token refreshing was a preview feature that was never fully implemented.

In the BotBuilder-Samples repo  there is a sample called "Bot Authetication MS Graph" ([C#](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/24.bot-authentication-msgraph) and [Node](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph)) that show the code for the type of logic you're looking for.

**Comment by thejasondt** [comment]
To confirm, currently I use:

connector.getUserToken - which always returns the expired 1 hour token. Is this what you mean by oauthPrompt? This returns the token but not whether it is expired (though it obviously does after 1 hour), are you recommending I do a check on that then log the user out myself? Is this the token you recommend checking?

If so this would log the user out every hour.

Otherwise, with every message I would have to check my saved long-term token myself before continuing.

Can you clarify what you recommend please.

**Comment by Jeffders** [comment]
Currently the bot service token store follows only the typical OAuth2 protocol, which includes retrieving the first access token from the identity provider. If you are using an identity provider that requires additional token exchanges, then our recommendation is for you to acquire and manage that token yourself.

**Comment by jameslew** [comment]
@thejasondt Jason; does that answer your question?  If so, would like your confirmations so we can resolve this item.  Thank you!

**Comment by jameslew** [comment]
Closing, please reactivate if you have further questions.
