### ISSUE TITLE
Telagram Webhook not send preCheckoutQuery to my bot

### ISSUE THREAD

**Issue by 4ININ** [microsoft/BotFramework-Services#209]
I trying get preCheckoutQuery from telegram webhook
After configure webhook https://dev.botframework.com/ was set correctly like
{"ok":true,"result":{"url":"https://telegram.botframework.com/api/telegram/my-bot/secret","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}
My endpoint myhost/api/messages
After this steps my bot handle messages correctly, but preCheckoutQuery from sendInvoice does not sended on my bot

please check my example project
https://github.com/4ININ/telegramWebhookPreCheckoutQueryIssue.git

Check this [Payment diagram process](https://raw.githubusercontent.com/4ININ/telegramWebhookPreCheckoutQueryIssue/master/TranzzoPaymentDiagram.png) 
In this diagram, instead of tranzzo can be any other payment provider

Becouse preCheckoutQuery is one of the optional parameter of Update object:
https://core.telegram.org/bots/api#update
As you can see, the Update object can also return message field, inline_query field etc.
There must be a way to get Update object via webhook. I am almost completely sure that is a problem with the Telegram connector

**Comment by v-kydela** [comment]
Linking: https://github.com/microsoft/botframework-sdk/issues/5828

**Comment by 4ININ** [comment]
@v-kydela, @craigjensen any feedback?

**Comment by jameslew** [comment]
Hello @4ININ , thanks for the report, and sorry for the delay.  We've dug into this and don't currently have Update implemented in the Telegram connector i.e. it's new feature work rather than a bug and will take some investigation/planning.

We will put it on our backlog to evaluate for future implementation, however I cannot provide an ETA at this time given our current backlog and committed work.

It's probably more work than you're interested in taking on, but if you want to use your current investment before we have the feature ready, you could utilize the bot framework sdk adapter interface and implement your own "telegram adapter" as a workaround.  There are a number of adapters for other channels already implemented in the Bot Builder Community here on github as examples.
