### ISSUE TITLE
Removing Messages From DirectLine Cache - GDPR Compliance

### ISSUE THREAD

**Issue by Jakob-vdH** [microsoft/BotFramework-Services#219]
Hi all,

I am searching for a way to actively remove conversation messages from the directline cache. I've seen from this issue microsoft/BotFramework-DirectLineJS#119 that the messages are only stored for 24 hours, but the conversations with the users of our customer could hold sensitive information and for the customer storing these messages for 24 hours is seen as an unnecessary risk. Is it possible to forcibly clear the conversation's messages from the directline cache?

Thank you very much for your help,

Jakob

**Comment by Jakob-vdH** [comment]
Is it correct, that using the new Direct Line App Service Extension, no messages would be cached by the Direct Line Extension, hence resolving my issue altogether?

Thank you very much for your help during this hard times.

**Comment by Jeffders** [comment]
Hello,

There is not a capability to flush the messages for a conversation or user in Direct Line sooner than the 24 hour limit. This is something one could do with Update and Delete activities that we have in our backlog but do not have any delivery date for. I will add this as a scenario for that feature.

For Direct Line App Service Extension, you are correct that there is no cache, because DL ASE is always just sending the messages to either the client or the bot directly. So if you want to get around the 24 hour issue, then I would recommend using DL ASE.
