### ISSUE TITLE
Please add documentation on retrieving user profile details from Alexa channel

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotFramework-Services#239]
### Use this [query](https://github.com/Microsoft/botbuilder-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Currently there is no documented way of retrieving User Profile from Alexa channel. The same is available for Teams channel.

**Describe the solution you'd like**
Need a method that would request the Alexa user to consent to data sharing
Need a method that would get the user profile data from Alexa channel

**Describe alternatives you've considered**
I have looked at the way of using Alexa Adapter from BF Community, but I would like to leverage the Alexa channel which is more straight forward and main stream.

I have also considered asking the same on Stackoverflow, but looks like we dont have any answers from the team.
https://stackoverflow.com/questions/63017704/extracting-user-profile-data-from-alexa-channel-address-email-phone-number-n

**Additional context**
We need more details of the user than just his UserId, to tag him against a relevant account on our database.

[enhancement]

**Comment by NickEricson** [comment]
@saikumaru The Alexa channel is actually running the Alexa adapter you linked at it's core. So, almost always, the method is the same.

@garypretty Do you have any docs on how to get the linked account / user profile info for Alexa?

**Comment by saikumaru** [comment]
@garypretty please can you advise us.
We would really need this piece of data in order to extend our Bot to wider audience.

**Comment by saikumaru** [comment]
@NickEricson can you please recheck if the right person was tagged and if you can reassign appropriately.

I need this information before I can publish the Alexa skill in marketplace. If you can let me know with a Yes/No about the possibility with current state of channel libraries, it would very much helpful.

Thank you!

**Comment by NickEricson** [comment]
Hi - As you probably know Alexa gives can give you the user id of the speaker and device owner. The easiest way to get these ids is from the ChannelData in the Activity. The ChannelData will include the full SkillRequest from Alexa.

https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#request-body-syntax

see: session.user.userId and context.System.user.userId

If you need to find out other information about the user you need to configure what information you want using permissions in Alexa:
https://developer.amazon.com/en-US/docs/alexa/custom-skills/configure-permissions-for-customer-information-in-your-skill.html

For example: I set a skill up to have these permissions:
![image](https://user-images.githubusercontent.com/11326851/89697986-b388af80-d8d3-11ea-84d9-ef1f23863227.png)

This gives your bot permission to ask for those bits of data about a user. The user will need to consent to give that data to your bot. That is done, from your bot, by using an "Ask for Permissions consent Card". Also the docs note if a customer adds your bot they should be prompted at that time.

If done from the bot this card will show the user a message (you can customize it). They will then need to go to their Alexa App (i.e. on their phone) and set those permissions. After they have done that you can make calls to Alexa from your bot to get the extra information about the user (in my case, from the picture above, name and Email address).

I'll list out these steps for a C# bot, other languages are similar.

First, in C# because of you need to worry about schema transforms more, we have a nuget package you can download to help with this. It is here:
https://www.nuget.org/packages/Bot.Builder.Community.Adapters.Alexa.Core

_Determining if you have permissions to get user data from Alexa_
Look at the documentation for the SkillRequest. The user node will have additional data if Alexa believes you have the permissions you need. If you attempt to get user information for someone who hasn't given all the permissions you need you will get a 401 response. So that is the lazy way to tell.

_How to get the user data_
I use `Alexa.NET.CustomerProfile.CustomerProfileClient` which is included in the package I mentioned before. You can bypass that if you would prefer.

```
// Extract full SkillRequest. You may not always need this or want to do it a faster way
var channelData = turnContext.Activity.ChannelData;
var skillRequest = JsonConvert.DeserializeObject<SkillRequest>(JsonConvert.SerializeObject(channelData));

// These are the permissions from the image above
var nameAndEmailPermissions = new List<string>
{
    CustomerProfilePermissions.FullName,
    CustomerProfilePermissions.Email
};

// Make the call to Alexa to get the additional user info. This uses the auth token in the request to complete the 
// call - if you haven't configured your skill to ask for those permissions or the user hasn't given you those permissions
// the call will fail.
var personProfileClient = new CustomerProfileClient(skillRequest);
var personName = await personProfileClient.FullName().ConfigureAwait(false);
```

_How to ask permission to get user data_
They should be asked when they add your app but you can, and should, also ask (if the above call fails) with an AskForPermissionsConsentCard card.

```
const string message = "Please give me permission to get your user info from the Alexa App";
var activity = MessageFactory.Attachment(new AskForPermissionsConsentCard() { Permissions = nameAndEmailPermissions }.ToAttachment(), message);
await turnContext.SendActivityAsync(activity).ConfigureAwait(false);
```

When testing this I did not get a pop-up in my Alexa App (phone). Instead I needed to configure it by going to my Skill (More -> Skills & Games -> Dev -> (pick your skill) -> Settings -> Manage account permissions -> pick permissions and save). That is just an FYI that you may want to keep in mind that people won't have their phone or may not get an immediate notification.

**Comment by saikumaru** [comment]
Thank you for your elaborate reply @NickEricson this is really helpful.
I will go back and try the series of steps you have outlined.

Just wondering if you will be adding the same to the channel specific documentation for future reference.

**Comment by NickEricson** [comment]
Hi @saikumaru - Let me know how it goes.

I will think about how we can improve our documentation. This would be a good addition.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Documentation and resources provided

**Comment by NickEricson** [comment]
Documentation link: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/Documentation/how-to-user-information.md
