### ISSUE TITLE
Ability to retain conversation history in Directline Speech

### ISSUE THREAD

**Issue by collegewap** [microsoft/BotFramework-Services#244]
## Feature Request

**Is your feature request related to a problem? Please describe.**

As mentioned in https://github.com/microsoft/BotFramework-WebChat/issues/2573, directline speech does not support retaining conversation history.

**Describe the suggestion or request in detail**

Since the [a.direct-line-speech](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech ) is the preferred way to enable speech in a bot, it should have an option to pass the previous token to retrieve the conversation history.

[Enhancement]

**Comment by nisheetjain** [comment]
Thanks for reporting this issue, 

Have you considered using 'Conversation_Conversation_Id' property to pass an existing conversation id to allow retaining/resume an existing conversation

Usage:
`            botFrameworkConfig.SetProperty(PropertyId.Conversation_Conversation_Id, conversationId);
`

FYI @compulim , @cwhitten

**Comment by compulim** [comment]
AFAIK, conversation history is not preserved because there are no service backends for conversation management. This is also true for Direct Line App Service Extension, which shares the same architecture as DLSpeech.

Setting the conversation ID will not retrieve the past conversation history as there is no conversation management service between the bot and the client.

When the team designed the DLSpeech protocol, it was designed as a protocol for transcript-less experience, such as smart display, headless home assistant, and telephony gateway. That's why we ship the smart display sample and promote it as part of the DLSpeech protocol. Unlike Direct Line channel, the protocol is not designed to support transcript.

Any thoughts?

**Comment by nisheetjain** [comment]
@collegewap 

here is the [SetProperty API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.dialog.dialogserviceconfig.setproperty?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Dialog_DialogServiceConfig_SetProperty_Microsoft_CognitiveServices_Speech_PropertyId_System_String_) that you will need to pass the conversationId correctly.

Does this help?

**Comment by arturl** [comment]
@collegewap, can you try the suggestion below and let us know if it worked for you?

**Comment by arturl** [comment]
Workaround provided, if the solution doesn't work feel free to reactivate.
