### ISSUE TITLE
"Title" keyword is added to Facebook when using adaptive cards with actions

### ISSUE THREAD

**Issue by kandelabr** [microsoft/BotFramework-Services#275]
## Version
Azure bot framework channel registration, Facebook channel

## Describe the bug
When using adaptive cards on Facebook channel, with actions or in carousel, "Title" is added to the card. On webchat channel everything looks fine.

## Expected behavior
"Title" keyword should not be visible. Since title is required to be sent to Facebook, there should be an option to provide meaningful title instead of just hardcoded "title"

## Screenshots
![action_carousel2](https://user-images.githubusercontent.com/2485533/105333022-899f1d00-5bd5-11eb-990f-3632e2b7d75a.PNG)
![action](https://user-images.githubusercontent.com/2485533/105333033-8c017700-5bd5-11eb-8e17-9c046d6710b6.PNG)
![action_carousel](https://user-images.githubusercontent.com/2485533/105333037-8c9a0d80-5bd5-11eb-8cbb-95e5c849a89c.PNG)

## Code 
Single image with actions:
[action.txt](https://github.com/microsoft/botframework-sdk/files/5848334/action.txt)
Carousel:
[action_carousel.txt](https://github.com/microsoft/botframework-sdk/files/5848336/action_carousel.txt)

**Comment by NickEricson** [comment]
@kandelabr - Thank you for reporting, I will look into what we can do.

**Comment by NickEricson** [comment]
Hi @kandelabr,

Adaptive Cards have a Title field

https://github.com/microsoft/AdaptiveCards/blob/9330134a661a4e15c6a066d14ceec1dd031bdba7/source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs#L115

that has been deprecated. I contacted the Adaptive Cards team and they are considering adding something new that would have a similar meaning... but the design and review can take time. I suggest we start using the AdaptiveCard.Title field for now. If, later, AdaptiveCards support another way to do this we can change things to match that new property.

You would create an Adaptive card like:
```
new AdaptiveCard {
 Title = "Card Title",  // using existing field.
 Body = new List<AdaptiveElement>
 { ... }
}
```
The resultant Card in Facebook would have `Card Title` instead of `Title`.

Does that work for your scenario?

**Comment by kandelabr** [comment]
hi @NickEricson 

yes that would be perfect. Thank you very much.

**Comment by NickEricson** [comment]
Hi @kandelabr  - this change should be deployed world wide now. Let me know if you see any issues.

**Comment by kandelabr** [comment]
hi @NickEricson, working great now. Thanks a lot.
