### ISSUE TITLE
Does Direct Line support group chat

### ISSUE THREAD

**Issue by jrmcdona** [microsoft/BotFramework-Services#285]
Hello,
Does Directline support two people chatting with a bot in the middle to facilitate the conversation?

**Comment by cwhitten** [comment]
Transferring to the services repository for discussion.

**Comment by dandriscoll** [comment]
The Direct Line API and infrastructure was designed to support multi-user chat. I suspect that if you try it, you'll find that it works.

Since we built it, we've found that multi-user scenarios are extremely uncommon, and much of the machinery around Direct Line (notably Web Chat) does not feature multi-user capabilities.
