### ISSUE TITLE
Getting 200 for /conversation/{id}/upload?userId={id} but no attachment in stream

### ISSUE THREAD

**Issue by ppapebright** [microsoft/BotFramework-Services#310]
The bot is sending back this message in the stream after uploading a file to the conversation via this method:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#upload-one-attachment

**"text": "Looks like you tried to send an attachment. Currently, I can only process text. Please try sending your message again without the attachment.** ",

Is there some setting I need to use to get it to accept images and files?

```json
  "activities": [
    {
      "type": "message",
      "id": "Fiq3i5iaAvEYCoARyGcUv-6|0000004",
      "timestamp": "2021-07-23T01:41:53.7085346Z",
      "channelId": "directline",
      "from": {
        "id": "2f74c4e1-339e-49d7-b673-63f61c9349af",
        "name": "DocSquad_Bot",
        "role": "bot"
      },
      "conversation": {
        "id": "Fiq3i5iaAvEYCoARyGcUv-6"
      },
      "text": "Looks like you tried to send an attachment. Currently, I can only process text. Please try sending your message again without the attachment. ",
      "inputHint": "acceptingInput",
      "attachments": [],
      "entities": [],
      "replyToId": "Fiq3i5iaAvEYCoARyGcUv-6|0000003"
    }
  ],
  "watermark": "4"
}
```

**Comment by MichaelHaydenAtMicrosoft** [comment]
@ppapebright - Our apologies here, but currently PVA doesn’t support handling activity with attachment natively, which is by design. and engine has not made any code change in this area since GA. 

You can also check the ticket that Steven attached above, which has a similar root cause. If this is not related to a PVA project, please feel free to re-open providing additional details.
