### ISSUE TITLE
ShowTypingMiddleware not working in SLACK

### ISSUE THREAD

**Issue by Anshul21** [microsoft/BotFramework-Services#332]
**Is your feature request related to a problem? Please describe.**
show typing middleware doesn't work in slack.

**Describe the solution you'd like**
Expected behavior is to see bot is typing so that user knows bot has received the message.

**Describe alternatives you've considered**
n/a

**Comment by stevkan** [comment]
@Anshul21, I tested this with a colleague and what we were able to determine is the `typing` activity, whether from the middleware or as an independent activity, is not being honored when sent to Slack. I am unsure if the issue is on the BotFramework Services side or something with Slack, itself.

@Services team - who would be the right person to own this item for further investigating?

**Comment by bobokids** [comment]
Shiyi, could you help to take a look?

**Comment by ssss141414** [comment]
Investigating.
