### ISSUE TITLE
Directline - internal server error 500, happening intermittent, URGENT! 

### ISSUE THREAD

**Issue by gjorgjevski** [microsoft/BotFramework-Services#337]
Our backend project:  .NET Core 3.1
Using Directline and Microsoft webchat.

## Describe the bug
We are getting internal server error from Directline channel and its intermittent. There is no a specific case when you will get this error its just random and its happening. It can be for example if you call the same directline call for 10 times the error can happen 3 times. 3 of 10 .

## To Reproduce
1. There is not a specific behavior when this is happening, its very random and it is happening intermittent.
2. If you do a couple of calls to that client specific Directline channel , from 10 times 3 times it will return 500 error using the same call.

## Expected behavior
This internal server error should not be happening at all.

## Screenshots

![problem1](https://user-images.githubusercontent.com/35025012/166916498-8e6e9b86-c93b-4fb9-822d-961f2a66bec0.PNG)
![problem2](https://user-images.githubusercontent.com/35025012/166916506-771216e0-6b54-4cf9-8e74-af857d7a7865.PNG)
![problem](https://user-images.githubusercontent.com/35025012/166916507-69cd982e-b9be-4819-9d60-23529c2ee7bd.PNG)

**Comment by bobokids** [comment]
https://dataexplorer.azure.com/clusters/botframeworkprod/databases/bfwprodKusto?query=H4sIAAAAAAAAA22QMW/DIBCF9/yKa5bYkpGBALGjukunrlWnLhUOh4JkmwRjpa3644uTtMoQCZ2OE9+7xwt4nHCMI1/8wGmPASG6Pg10f4AnMDrifM845ZxQSSh/o3R7Pu/5HeTxDrK5h7Q+vhhoGlgG50lMOFGtqKTUnLBWWyKU3ZCaMZUE1BrtWrLloiz/eH/AoKPzw8dVppJmh4xpWdfKaKEqRNsqZBWvhKmsvIUDjlMXn71BeHBDxigrgFM6l9SJuRN0PRcxO8bPiIMBDCHgERrIbvj07RDHk4t7WMnV/Hqc+l4H951i8VF3zc5PQ8zyAqx2HZrXa+CXubPZRTaH9gvaZOY/ywIU7fOyLG7sJvmQrGA4R77bp92/IEwteMEBAAA=

requests2
| where timestamp > datetime(2022-05-02T00:00:00Z)
| where timestamp < datetime(2022-05-07T00:00:00Z)
| where botId == "rio-test-6b4855a2-1baf-46f7-9116-0763ef351"
| extend errreq = (resultCode startswith '5')
| summarize total=count(), failedRequests=countif(errreq) by bin(timestamp, 60m)//, resultCode
| render timechart 
![image](https://user-images.githubusercontent.com/19182479/169347178-2f56fd55-53ad-4208-9f8f-2a4c01ff4001.png)

we only see few failed requests in that period caused by Redis call failures.

**Comment by bobokids** [comment]
Hi @gjorgjevski , do you still repro the issue. We didn't see similar pattern in the bot service log data.

**Comment by gjorgjevski** [comment]
Seems it got resolved by itself. But i am more than sure that came from
some changes in cloud.
Thank you.

**Comment by bobokids** [comment]
Closed the issue for now. May reactivate this issue if we have proper repro steps to help the investigation.
