### ISSUE TITLE
User replies in Teams team chat don't prefix with the @bothandle after 1st input, so get ignored by bot

### ISSUE THREAD

**Issue by dividor** [Microsoft/BotFramework-Services#35]
Running v4 node.js bot, we have deployed to a teams channel. If a user starts a new private direct chat with the bot (ie "Message bot"), everything works really well, things are stable. 

However, if the user starts a chat with the bot in a team by using the handle (eg @Otto), it starts a thread, and works well for 2 interactions, then becomes unresponsive.

So for example:

1. User goes to the group with the chatbot
2. User types "@Otto hi"
3. New thread is started in the Teams window, bot responds
4. In the "Reply" on the thread, user asks an FAQ question
5. Bot responds
5. User types another question, nothing happens. Bot logs show no traffic

Looking at the teams UI (see attached), it seems that when the user enters something, the input is automatically prefixed with the bot handle @Otto the first time, but after that this doesn't happen, so the input is ignored and the user thinks the bot has frozen.

If in a 'Reply' thread with the chatbot, the user should not have to remember to prefix all replies with the handle, from a user's perspective they are already chatting with the bot. This issue hit every single one of our users, who thought the bot had 'frozen'.

How can we resolve this please, makes using the bot in teams difficult?

![teamschat](https://user-images.githubusercontent.com/8402586/50046744-745e7880-0076-11e9-9b0e-c53394e46ee8.PNG)

**Comment by v-kydela** [comment]
[This is by design](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-channel#-mentions) 

It may seem annoying to have to explicitly mention the bot every time you want the bot to respond, but consider if it was the other way and the bot was automatically mentioned. You'd have to remember to remove the bot's mention every time you're talking to a teammate and don't want the bot to respond. Conversations in Teams channels are designed to work with many people in one conversation, so bots only respond when mentioned because otherwise they would respond to lots of messages that aren't meant for them.

Notice that if the last message in a conversation is from a bot, the bot will automatically be mentioned when you click the reply button to open the text input box. If the input box is already open and there's no mention, you can deselect that conversation to make the reply button appear. Also notice that users can chat with a bot privately if they don't want to have to mention the bot to get replies.

If you still think Teams needs more functionality to accommodate your users, I recommend sending some feedback through the Teams app.
