### ISSUE TITLE
Custom endpoint make settings unaccessible

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/BotFramework-Services#41]
If I change the Messaging endpoint to a different one outside the domain azurewebsites, the application settings could not longer being accessed:

![botappazureserviceportal3](https://user-images.githubusercontent.com/952392/51926674-9e5dc700-23a6-11e9-8906-e6ee73f920dc.PNG)

![bugappazureserviceportal](https://user-images.githubusercontent.com/952392/51926582-72424600-23a6-11e9-8120-2260e5b38784.PNG)

![bugappazureserviceportal2](https://user-images.githubusercontent.com/952392/51926585-72424600-23a6-11e9-9ad2-1342c7d49d9b.PNG)

**Comment by v-kydela** [comment]
Hi @mahomedalid 

This is actually expected behavior. The two blades under App Service Settings draw their data from an entirely different resource. A Web App Bot resource is just like a Bot Channels Registration resource that's assumed to be connected to an App Service resource. The way the two resources are connected is through the messaging endpoint in the settings blade. If you change that endpoint to something that's not associated with an App Service resource then there's nothing for the App Service Settings to refer to.

**Comment by drub0y** [comment]
I think we're just asking if there could be a better user experience in this situation. Couldn't the blade actually detect that it's a non-azure web app URL and, instead of a bunch of red warning messages, show a message that guides the user in the right direction by saying something like:

> Application Settings can not be edited because the bot's messaging endpoint is configured to point to someplace that does not appear to be an Azure Web Application: <show current messaging endpoint value here>

I don't love that wording, but hopefully that illustrates the point. Additionally you could include a link back to the settings where the messaging endpoint is configured so they can easily jump there to fix it. Additionally you could even look for ngrok specifically in the messaging endpoint and provide an even better explanation and guidance.

**Comment by CoHealer** [comment]
Reopening for inclusion in pending feedback review.
