### ISSUE TITLE
Not clear which Azure resource to use when searching for "bot"

### ISSUE THREAD

**Issue by codefoster** [Microsoft/BotFramework-Services#43]
## Versions
Not an SDK issue. This bug relates to Azure.

## Describe the bug
In the Azure web portal, when you attempt to search for resources using the search term "bot", it's very unclear to average developers which of the results to choose. Not only are there WebApp bots and registration bots, but there are a lot of other resource types mixed in there.

## To Reproduce
1. Go to the Azure web portal
2. Create a new resource
3. Search for "bot"
4. Trouble yourself over which resource type to choose.

## Expected behavior
A clearer, more concise list of resource types.

## Additional context

[bug]

**Comment by sgellock** [comment]
@Andrea-Orimoto this is a portal issue.  moving over for your to consider how and when to address

**Comment by Andrea-Orimoto** [comment]
@codefoster thanks a lot for your feedback, I agree, it can be confusing. We're working right now to reorder at least the bot results.

Not sure we can affect any of the other results, since they might have "bot" in their keywords, because they might be somehow related.

I'm going to close this issue since it is in our radar. Feel free to re-activate or create a new one if needed. Finally, for Azure specific feedback you can find a feedback and a support link in the azure portal itself.

Thanks a lot
Andrea

**Comment by codefoster** [comment]
Great. Thanks.
