### ISSUE TITLE
Markdown rendering - Horizontal Rule

### ISSUE THREAD

**Issue by mekinney** [Microsoft/BotFramework-Services#47]
When rendering a horizontal rule, the rule is not displayed and all normal text prior to the rule is rendered as H2.

The rendering is the using webchat, portal.azure.com, the emulator and the twilio channel.

Below is the code to created the message with simple markdown and I've attached a screen shot of the emulator window.

Also, is this the correct project to bring up rendering issues?  I have some others that are twilio specific.

Thanks in advance.

Mike

```csharp
public static IMessageActivity BuildLineBreakBug(ITurnContext turnContext, bool addLine)
{
    var text = new StringBuilder();

    text.AppendLine("Line 1 **Bold text**");
    text.AppendLine("Line 2 Normal text here.");
    if (addLine)
    {
        text.AppendLine("---");
    }
    text.AppendLine($"Line 3 - Line break between 2 and 3 = {addLine}");
    text.AppendLine("Line 4 - Normal text here.");

    var response = turnContext.Activity.CreateReply(text.ToString());

    return response;
}
```
![rendering bug](https://user-images.githubusercontent.com/7552362/52380188-b0340f80-2a21-11e9-942a-767c3570735a.JPG)

**Comment by mdrichardson** [comment]
You're correct. This does appear to be a bug and needs to be fixed. In the meantime, you can accomplish what you're looking for using `***` (asterisks) or `___` (underscores).

![image](https://user-images.githubusercontent.com/40401643/52439441-5d656100-2ad0-11e9-88a0-be9ca7e178ce.png)

**Comment by mdrichardson** [comment]
As it turns out, this is not a bug.

You might be more familiar with using `---` for horizontal rule because many utilities (GitHub, included?) follows [Don Gruber's original specs for Markdown](https://daringfireball.net/projects/markdown/syntax#hr), which came out way back in 2004. Bot Framework's WebChat, which is used to render WebChat *and* emulator, uses [markdown-it](https://www.npmjs.com/package/markdown-it), which uses the continually-updated [CommonMark spec](https://spec.commonmark.org/). It treats `---` and `===` as a [Settext Heading](https://spec.commonmark.org/0.28/#setext-headings) and makes the text on the previous line a heading.
