### ISSUE TITLE
Register a web hook to receive messages in Direct Line

### ISSUE THREAD

**Issue by hpksp** [Microsoft/BotFramework-Services#63]
Hi, 

Having an option to register a web hook per conversation/all conversations (in addition to long polling or web socket) would help greatly for proactive bot scenarios.

For example when an event gets triggered on our application side, we can send a notification to the respective user. Let's assume that the user is using Direct Line client and he/she is offline at the time of the notification being sent. When he/she comes back online (resume conversation + use watermark) after 3 days that notification would no longer available in the Direct Line cache.

If we can have a web hook in place, at least we can store the notifications for user to access them later. In my opinion, maintaining an intermediate server by us would be pointless/expensive, that's why I think this feature would come in handy :)

I would love to know what you guys think. If this is a dumb idea or if there's an alternative approach. please let me know. Thanks in advance.

P.S: similar request [1063](https://github.com/Microsoft/BotBuilder/issues/1063)

**Comment by EricDahlvang** [comment]
Hi @hpksp 

The Direct Line cache is intended to enable connection stability, not a persistent conversation history.  Since the Bot either sends or receives all messages going through the Direct Line service, it is possible to utilize an **[ITranscriptStore ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.itranscriptstore)** implementation to provide a persistent conversation history.  

The Direct LIne channel also provides a method for re-hydrating previous activities into a conversation: **[SendConversationHistoryAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.sendconversationhistoryasync)**  A rudimentary example of its usage can be found here: [22.conversation-history/ConversationHistoryBot.cs#L113](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/22.conversation-history/ConversationHistoryBot.cs#L113)

**Comment by hpksp** [comment]
Many Thanks @EricDahlvang :)
