### ISSUE TITLE
Inconsistent code generated by yeoman generator v/s Azure portal

### ISSUE THREAD

**Issue by erikamenezes** [Microsoft/BotFramework-Services#68]
**Version:** 4.3.4

**Description**
Echobot created using the yeoman generator and generated through the azure portal create confusion because of inconsistent api usage.

Yeoman generated code uses bot.onTurn(context): 
![image](https://user-images.githubusercontent.com/9581213/55658450-90fff700-57b2-11e9-92a8-4b336570acce.png)

Azure portal generated code index.js uses bot.run(context) which is an outdated api and no longer exists: 
![image](https://user-images.githubusercontent.com/9581213/55658433-7c236380-57b2-11e9-9732-7eb8a159435e.png)

**Repro steps:**
1. Generate echo bot using yeoman generator (yo botbuilder)
2. Generate echo bot through azure portal (Web app bot> Node.js > Echo bot) and download source code
3. Examine index.js in source code for bots created using 1. and 2.

**Expected behavior:**
Code (index.js) generated through the portal should use the current v4 api using bot.onTurn(context)

--

**Comment by mdrichardson** [comment]
This was fixed in [this commit](https://github.com/Microsoft/BotBuilder-Samples/commit/428a551a097f23ffc42d321bbe78ec371377fc3d), but has yet to make it to the latest version of [`generator-botbuilder`](https://www.npmjs.com/package/generator-botbuilder?activeTab=readme). You can use the dev build (which has the updated template) by following [the instructions here](https://www.npmjs.com/package/generator-botbuilder?activeTab=readme#optionally-using-development-builds).

Quick note: `myBot.run()` is actually newer that we'll be rolling out to samples since we made some pretty big changes to [ActivityHandler](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/activityHandler.ts). You can check out [this Samples branch](https://github.com/Microsoft/BotBuilder-Samples/tree/samples-work-in-progress) if you need help implementing it.
