### ISSUE TITLE
Directline post activity gives 'Service Error' - Same as #54

### ISSUE THREAD

**Issue by ManjulaMalaiarasan** [Microsoft/BotFramework-Services#73]
I am facing the same issue mentioned in #54.
-  Directline post activity throws {code: "Service Error"} for random messages since yesterday. 
- Faced 25 in the last 24 hours period so far

Microsoft App ID: 7cbd578f-5c92-4fa4-b2c6-142e307a06ef
Bot Handle: IBMSdx-ON-151
Conversation Id: BtAajXujmRiA8wYxOl1t0E-9
"timestamp":"2019-04-10T12:17:34.195Z"

**Comment by vincec-msft** [comment]
This error and many others in the 24 hours ending 2019-04-10T12:00Z were caused by activities that were too large. See if you can trim down your activity size by using attachments rather than inline data.

I thought that we returned a message about the size being too large in the response body but I'll have to test that. If not, we will so this will be easier to diagnose.
