### ISSUE TITLE
First Message Error on Channel & Emulator

### ISSUE THREAD

**Issue by ikivanc** [microsoft/BotFramework-Services#75]
Hi Team,

I use v 4.3.2.

Yesterday I got first message below first message error on Teams channel, after creating brand new application on Azure Web App, Echo Bot template. It worked fine on webchat test.

![image](https://user-images.githubusercontent.com/118657/56704566-45d46680-6716-11e9-8967-d85e4a13a29d.png)

Today I got the same error in my emulator after first message again. **This issue happened twice**.

Is it a known issue? I just used the template on Azure.

Thanks.

**Comment by v-kydela** [comment]
@ikivanc - Thank you for the question!

Based on your issue, I just made a new echo bot and tested it in Teams and the Emulator. I was unable to reproduce the problem, so it's nearly impossible to speculate about what the problem might be. Please have a look at the [troubleshooting](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems) documentation. A good first step is to check the Channels blade in your bot resource because that can show errors:

![image](https://user-images.githubusercontent.com/41968495/56758914-8a7af480-674c-11e9-9ce6-69520ef08761.png)

You can click on the errors/warnings button to get more information in a popup:

![image](https://user-images.githubusercontent.com/41968495/56759058-e8a7d780-674c-11e9-9392-331ee42330b0.png)

If you have Application Insights enabled you can check that for errors too.

Beyond that, the best thing for you to do is download the source code and [test it locally using ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) to identify the error.

**Comment by ikivanc** [comment]
Hi @v-kydela ,

I checked application insights logs however I couldn't find Teams channel log, 
In Application Insights there are only "webchat" logs under "exceptions" > "customDimensions" > "Channel ID".

I created 2 new projects on portal to reproduce, but couldn't reproduce, that's why I posted here if anyone faced with same issue, I'll follow and let you know if reproduce again.

![image](https://user-images.githubusercontent.com/118657/56891547-840ab680-6a85-11e9-8c94-8c069e24e1cb.png)

Thanks & Regards.

**Comment by v-kydela** [comment]
All right, I'll wait and see if you can reproduce it again. And please do try testing with ngrok.

The only times I've seen the Unknown error in Teams is when the bot tries to send too many messages too quickly. It's a throttling error. But in your case, it looks like there was only one message.

**Comment by v-kydela** [comment]
@ikivanc - Are you still working on this?

**Comment by ikivanc** [comment]
@v-kydela I haven't reproduced the same error again. Just in-case anyone face with this issue. We can close this.
