### ISSUE TITLE
Facebook Channel - Bot-service receives 2 messages when user uploads an image with a text msg 

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-Services#96]
### Setup
Botbuilder SDK: NodeJS v3.16
Channel: Facebook Messenger

### Issue
When a user from FB Messenger channel uploads an image along with text message (in a single msg), bot service (using NodeJS v3.16 SDK) receives 2 separate messages, one with the attachment and one with the text message. 
Hence bot service thinks that the user has sent 2 messages and replies to the user twice (for both messages).

Is there any way bot service can receive both (text message and attachment) in a single message? OR a way to identify from the message data that these messages are split.

**Comment by EricDahlvang** [comment]
Hi @bhushanvadgave 

I think this is on the Facebook Messenger side.  Oftentimes, when the connector receives a message it will add the channel specific information to ChannelData while converting the message to the Activity protocol.  If you inspect ChannelData of the two messages coming from Facebook:

Id: xxxxxxxxxxrIO3N0LMGMm3KxkkNevMfSXJBdctHDpgmMstiVL32h6m6VEYBhxxxxxxxxxx
Text: test
```json
ChannelData: {
  "sender": {
    "id": "1892991417434002"
  },
  "recipient": {
    "id": "331206034292310"
  },
  "timestamp": 1564614162480,
  "message": {
    "mid": "xxxxxxxxxxrIO3N0LMGMm3KxkkNevMfSXJBdctHDpgmMstiVL32h6m6VEYBhxxxxxxxxxx",
    "seq": 0,
    "text": "test",
    "is_echo": false
  }
}
```

Id: xxxxxxxxxx-zuULpyFq1P49rIO3N0LMGMm3KxknhCIv_LPlQCTTS3i6k3Ig_4j5hWZ-xxxxxxxxxx
Text: 
```json
ChannelData: {
  "sender": {
    "id": "1892991417434002"
  },
  "recipient": {
    "id": "331206034292310"
  },
  "timestamp": 1564614162920,
  "message": {
    "mid": "xxxxxxxxxx-zuULpyFq1P49rIO3N0LMGMm3KxknhCIv_LPlQCTTS3i6k3Ig_4j5hWZ-xxxxxxxxxx",
    "seq": 0,
    "is_echo": false,
    "attachments": [
      {
        "type": "image",
        "payload": {
          "url": "https://scontent-atl3-1.xx.fbcdn.net/v/t1.15752-9/67602486_1427683790689440_2618584987061977088_n.png?_nc_cat=109&_nc_oc=AQlV7iGgPZvE18efxDcSWdRHKGujRcu8x4kozPHFYCzaZ-SGo_dp-djLp_DYGriojvkJ5-7yH5eVovqx2riKjnjC&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent-atl3-1.xx&oh=808ea32eefa2ef03327427bcf9c9c129&oe=5DE11CF3"
        }
      }
    ]
  }
}
```

I believe this indicates that Messenger is sending two separate messages, and the Bot Framework is just forwarding those on to the bot.  In order to handle this intelligently within the bot, you could add code to log the time whenever you receive a message with Text.  Then, when receiving a message with an attachment, check if it has arrived within a very short timespan of the text message ... and do not reply to the image message accordingly.  This is a hack, but one possible workaround.

**Comment by hcyang** [comment]
Hi @bhushanvadgave: any updates? If not, we may close this issue.

**Comment by CezaryMarcjan** [comment]
We'll close this by now. Please reopen if necessary
