### ISSUE TITLE
OnMembersAddedAsync method is not getting triggered when someone is added to a group chat in the GroupMe channel

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotFramework-Services#97]
I created a Web App Bot with the Echo Bot template on Azure and connected it to the GroupMe channel. Created a new group on GroupMe and added the bot to the group. 

- The main bot class code is as follows:

```
public class EchoBot : ActivityHandler
    {
        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(MessageFactory.Text($"Echo: {turnContext.Activity.Text}"), cancellationToken);
        }

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text($"Hello and welcome!"), cancellationToken);
                }
            }
        }
    }
```

- When I add a new member to the group or a new member joins the group, as per the code, the OnMembersAddedAsync method should get triggered and the Bot should respond back with 'Hello and welcome!', but it just echoes out the message that the new member has been added to the group.
 
![gh1_LI (2)](https://user-images.githubusercontent.com/48731427/62249860-542ec000-b3a0-11e9-9588-40953ba492c3.jpg)
![gh22](https://user-images.githubusercontent.com/48731427/62249982-98ba5b80-b3a0-11e9-9bc9-ca3c52b67105.png)

- Expected response should be 
```
xxxx has joined the group
ARREchoTestBot
Echo: Hello and welcome!
```

 

[bug]

**Comment by v-kydela** [comment]
The GroupMe connector appears to be sending those events to the bot as message activities rather than conversation update activities

**Comment by sphanley** [comment]
Any expected ETA on a fix for this issue? Because of the fact that these messages are coming through as message activities rather than conversation update activities, the ID(s) of the added user(s) aren't present on the message, which really limits the ability to directly interact with those users when they join the chat.

As an aside - it's worth mentioning that GroupMe sends slightly different system messages for the following three scenarios: 

* A new user who used a link to add themself to a chat where they've never been a member
* A user who re-added themself to a group where they've been a member in the past
* A user who is added to a group by another current member of that group

 I don't know if the Bot Framework has the capability to meaningfully differentiate these cases within a ConversationUpdate activity, but it would be great if this info can be preserved - even if it's just by including the text of the system messages generated by GroupMe.

**Comment by mickeydjw** [comment]
Assigning to myself for tracking purposes.   @sphanley I'll update you with an ETA here once I have more info for you.

**Comment by sphanley** [comment]
Thanks @mickeydjw! I really appreciate the support.

**Comment by mickeydjw** [comment]
@sphanley I haven't forgotten about you.  We're working on finding the right folks for help with the groupme issues.

**Comment by sphanley** [comment]
I appreciate the update @mickeydjw! I know how hard it can be sometimes to work across multiple teams and services. I'm looking forward to eventual movement on this and #101!

**Comment by getangar** [comment]
Hi there, I'm sorry if this is not the proper way to attach my request too. But the same issue happens also with the Web Chat channel.

**Comment by anusharavindrar** [comment]
@getangar, please open a  new issue in the Web Chat [repo](https://github.com/microsoft/BotFramework-WebChat/issues/new/choose) and explain your issue in detail. Thanks!

**Comment by arturl** [comment]
Thank you for the issue report and working with us to get to the detail.  We've evaluated the issue and determined that it doesn't fit in our current semester's schedule.  We have added it to our backlog for future planning, but do not have an ETA to offer at this time.
